// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSrukC2hFlkl1m750hKaB1bQTW5kGaevo',
    appId: '1:818473001596:web:ce12814f1dc2dccfd81ff9',
    messagingSenderId: '818473001596',
    projectId: 'sidesa-5cd04',
    authDomain: 'sidesa-5cd04.firebaseapp.com',
    storageBucket: 'sidesa-5cd04.firebasestorage.app',
    measurementId: 'G-BDBRH7SV5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0tQxrsdRwDKfQacwjSQlJ1QKAFjpqvk',
    appId: '1:818473001596:android:98541a8113c57b2bd81ff9',
    messagingSenderId: '818473001596',
    projectId: 'sidesa-5cd04',
    storageBucket: 'sidesa-5cd04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKTX-tvuD50uMHKMpTiBWouK3h98EAEM',
    appId: '1:818473001596:ios:73c94a51d414adbcd81ff9',
    messagingSenderId: '818473001596',
    projectId: 'sidesa-5cd04',
    storageBucket: 'sidesa-5cd04.firebasestorage.app',
    iosBundleId: 'com.example.siDesaCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfKTX-tvuD50uMHKMpTiBWouK3h98EAEM',
    appId: '1:818473001596:ios:73c94a51d414adbcd81ff9',
    messagingSenderId: '818473001596',
    projectId: 'sidesa-5cd04',
    storageBucket: 'sidesa-5cd04.firebasestorage.app',
    iosBundleId: 'com.example.siDesaCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSrukC2hFlkl1m750hKaB1bQTW5kGaevo',
    appId: '1:818473001596:web:edae21dbc910a753d81ff9',
    messagingSenderId: '818473001596',
    projectId: 'sidesa-5cd04',
    authDomain: 'sidesa-5cd04.firebaseapp.com',
    storageBucket: 'sidesa-5cd04.firebasestorage.app',
    measurementId: 'G-PCPVQM9HFY',
  );
}
